import {
  Banknote,
  Bell,
  Binoculars,
  Bird,
  Boxes,
  Clipboard,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  Coins,
  Copy,
  Crown,
  Diamond,
  Dribbble,
  Flag,
  Gamepad2,
  Gift,
  Globe,
  Hash,
  Home,
  LayoutGrid,
  Menu,
  MessageCircle,
  Minus,
  Moon,
  Music,
  Palette,
  PartyPopper,
  Plus,
  Radio,
  Search,
  Send,
  Shield,
  Star,
  Sun,
  Table,
  ThumbsUp,
  Ticket,
  Trash2,
  TreePine,
  TriangleAlert,
  Trophy,
  Tv,
  UserRound,
  Volleyball,
  Wallet,
  X,
  Rocket,
} from "lucide-react";

const ICONS = {
  banknote: Banknote,
  bell: Bell,
  binoculars: Binoculars,
  bird: Bird,
  boxes: Boxes,
  clipboard: Clipboard,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  circleDot: CircleDot,
  coins: Coins,
  copy: Copy,
  crown: Crown,
  diamond: Diamond,
  dribbble: Dribbble,
  flag: Flag,
  gamepad: Gamepad2,
  gift: Gift,
  globe: Globe,
  grid: LayoutGrid,
  hash: Hash,
  home: Home,
  menu: Menu,
  messageCircle: MessageCircle,
  minus: Minus,
  moon: Moon,
  music: Music,
  palette: Palette,
  partyPopper: PartyPopper,
  plus: Plus,
  radio: Radio,
  search: Search,
  send: Send,
  shield: Shield,
  star: Star,
  sun: Sun,
  table: Table,
  thumbsUp: ThumbsUp,
  ticket: Ticket,
  triangleAlert: TriangleAlert,
  trash: Trash2,
  tree: TreePine,
  trophy: Trophy,
  tv: Tv,
  user: UserRound,
  volleyball: Volleyball,
  wallet: Wallet,
  x: X,
  rocket: Rocket,

  // locate-fixed : LocateFixed,
  // volleyball: Volleyball,
};

function AppIcon({
  name = "circle",
  className = "",
  size = 16,
  strokeWidth = 2,
}) {
  const Icon = ICONS[name] ?? Circle;
  return (
    <Icon
      className={`inline-block align-middle ${className}`.trim()}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}

export default AppIcon;
